name: Keepalive
on:
  schedule:
    - cron: '0 0 */5 * *'  # 每5天触发
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s -o /dev/null "https://owidmewjfgvekhpjoxgu.supabase.co/rest/v1/?apikey=sb_publishable_RhhnLTk6OSQpnSU0AkvHow_jHFdfFY2"
